apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-yew-app
  labels:
    app: flask-yew-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-yew-app
  template:
    metadata:
      labels:
        app: flask-yew-app
      annotations:
        dev.okteto.com/auto-ingress: "true"
    spec:
      containers:
      - name: flask-yew-app
        image: ghcr.io/katapy/flask-yew-app:develop
        ports:
        - containerPort: 5000