name: Create Archive

on: [push]

jobs:
  ui_build:
    defaults:
      run:
        working-directory: ui

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build ui
        run: |
          pwd
          ls -a
          rustup target add wasm32-unknown-unknown
          cargo install trunk
          trunk build --release --public-url flask_yew_app
          
      - name: Archive dist folder
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ui/dist


  create_js_file:
    runs-on: ubuntu-latest
    needs: ui_build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
