name: Create Archive

on: [push]

jobs:
  ui_build:
    defaults:
      run:
        working-directory: ui

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build ui
        run: |
          pwd
          ls -a
          rustup target add wasm32-unknown-unknown
          cargo install trunk
          trunk build --release --public-url flask_yew_app
          
      - name: Archive dist folder
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ui/dist

  download_dist:
    defaults:
      run:
        working-directory: server/app/static
    runs-on: ubuntu-latest
    needs: ui_build
    steps:
      - name: download dist
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: server/app/static/dist
      - run: |
          mkdir js
          pwd
          ls -Ra
          echo "import init from \"/static/dist/`ls -R1 dist | grep index-.js`\";" > index.js
          cd js && echo "await init(\"/static/dist/`ls -R1 dist | grep index-.wasms`\");" >> js/index.js
      - name: Archive js folder
        uses: actions/upload-artifact@v3
        with:
          name: js
          path: server/app/static/js
      