name: Node CI

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Build ui
        working-directory: ./ui
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install trunk
          trunk build --release --public-url flask_yew_app
          
      - name: Archive dist folder
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: server/app/static